# Generated by Django 3.0.2 on 2020-05-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MarginClass',
            fields=[
                ('margin_class', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CI050',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearing_member', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('margin', models.IntegerField()),
                ('report_date', models.DateTimeField()),
                ('report_time', models.DateTimeField()),
                ('margin_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.MarginClass', verbose_name='MarginClass')),
            ],
        ),
        migrations.CreateModel(
            name='CC050',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearing_member', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('margin', models.IntegerField()),
                ('report_date', models.DateTimeField()),
                ('margin_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.MarginClass', verbose_name='MarginClass')),
            ],
        ),
    ]
